//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreAdmin
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class Tuote : IValidatableObject
    {
        public int TuoteID { get; set; }
        [Required]
        [StringLength(50)]
        public string Nimi { get; set; }
        [DisplayFormat(NullDisplayText = "tyhjä")]
        [Range(1, 1000, ErrorMessage = "Virhe")]
        [Required]
        public decimal Hinta { get; set; }
        [DisplayFormat(NullDisplayText = "tyhjä")]
        [Range(1, 100, ErrorMessage = "Virhe")]
        [Required]
        public decimal Veroprosentti { get; set; }

        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (Hinta < 0) {
                yield return new ValidationResult("Anna positiivinen desimaaliluku!");
            }
        }
    }
}
